os: linux

addons:
  apt:
    packages:
      - libcryptsetup-dev

language: rust
matrix:
    include:

        # MANDATORY CHECKS USING CURRENT DEVELOPMENT TOOLCHAIN
        - name: "format Rust source using current development toolchain"
          rust: 1.40.0
          before_script:
              - rustup component add rustfmt
          env: TASK=fmt-travis

        - name: "lint Rust source using current development toolchain"
          rust: 1.40.0
          before_script:
              - rustup component add clippy
          env: TASK=clippy

        # MANDATORY TESTING ON STABLE
        - name: "build using stable toolchain"
          rust: stable
          env: TASK=build
        - name: "build Rust docs using stable toolchain"
          rust: stable
          env: TASK=docs-travis
